config/routes.rb
Rails.application.routes.draw do
  resources :couriers do
    resource :packages
  end
  root to: 'couriers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord 
    has_many :packages, dependent: :destroy
  
    validates :name, presence: true, length: { maximum: 140 }
    validates :email, presence: true,
                length: { maximum: 140 },
                format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  end
  

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: %i[ show edit update destroy ]

  def index
    @couriers = Courier.all
  end

   
  def show
  end

  
  def new
    @courier = Courier.new
  end

  
  def edit
  end

  def create
    @courier = Courier.new(courier_params)

    respond_to do |format|
      if @courier.save
        format.html { redirect_to @courier, notice: "Courier was successfully created." }
        format.json { render :show, status: :created, location: @courier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to @courier, notice: "Courier was successfully updated." }
        format.json { render :show, status: :ok, location: @courier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @courier.destroy
    respond_to do |format|
      format.html { redirect_to couriers_url, notice: "Courier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_courier
      @courier = Courier.find(params[:id])
    end

    def courier_params
      params.require(:courier).permit(:name, :email)
    end
 
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

  def create
    @courier = Courier.find(params[:courier_id]) 
    @package = @courier.packages.new(package_params)
    @package.save

    redirect_to @courier
  end

  def show
  end

  def destroy
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.find(params[:id])
    @package.destroy
    
    redirect_to couriers_path(@courier)
  end

  private

  def package_params
     params.require(:package).permit(:tracking_number, :delivery_status)  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/views/couriers/_form.html.erb
<%= simple_form_for(courier) do |f| %>
  <% if courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courier.errors.count, "error") %> prohibited this courier from being saved:</h2>

      <ul>
        <% courier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.input :name %>
  </div>

  <div class="field">
   
    <%= f.input :email %>
  </div>
  <br>

  <div class="actions">
    <%= f.button :submit, "Push", class: "btn  btn-primary" %>
    <%= link_to 'Back', couriers_path, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/couriers/edit.html.erb
<div class="container">
	<h1>Editing Courier</h1>
	<%= render 'form', courier: @courier %>
</div>

app/views/couriers/index.html.erb
<p id="notice"><%= notice %></p>
<div class=container>
  <h1 class="text-center">Couriers</h1>
  <table class="table table-success table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Show</th>
        <th>Editing</th>
        <th>Delete</th>
      </tr>
    </thead>
    <% order = 0 %>
    <tbody>
      <% @couriers.each do |courier| %>        
        <tr>
          <td><%= order += 1 %></td>
          <td><%= courier.name %></td>
          <td><%= courier.email %></td>
          <td><%= link_to 'Show', courier , class: "btn btn-info"%></td>
          <td><%= link_to 'Edit', edit_courier_path(courier), class: "btn btn-success"%></td>
          <td><%= link_to 'Delete', courier, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Courier', new_courier_path, class: "btn btn-primary" %>
</div>

app/views/couriers/new.html.erb
<div class="container">
  <h1 class="text-center">New Courier</h1>
  <%= render 'form', courier: @courier %>
</div>

app/views/couriers/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-12">
      <p>
        <strong>Name:</strong>
        <%= @courier.name %> \
        <strong>Email:</strong>
        <%= @courier.email %>
      </p>
    </div>
  </div>
  
  <br>
  <div><h2 class="text-center">New package!</h2></div>

  <%= simple_form_for([@courier, @courier.packages.build]) do |f| %>	
    <p>	
      <%= f.input :tracking_number, :class => 'form-control' %>
    </p>
    <p>	
      <%= f.input :delivery_status, :class => 'form-control' %>
    </p>
    <p>		
      <%= f.submit "Create package", :class => 'btn btn-primary' %>
      <%= link_to 'Back', couriers_path, class: "btn btn-dark" %>
    </p>
  <% end %>
  <br>
  <table class="table table-success table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>Tracking_number</th>
      <th>delivery_status</th>
      <th>Data</th>
    </tr>
  </thead>
  <tbody>
    <% @courier.packages.each do |package| %>      
      <tr>
        <td><%= package.id%></td>
        <td><%= package.tracking_number %></td>
        <td><%= package.delivery_status %></td>
        <td><%= package.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
	
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>